import 'package:get/get.dart';

class LocalizationString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {

      //Bottom Nav Bar
      'home': 'Home',
      'flood_info': 'Flood Info',
      'flood_alert': 'Flood Alert',
      'profile': 'Profile',

      //Login Page
      'app_name': 'FFWC App',
      'welcome_login': 'LOGIN',
      'login_greetings': 'Welcome to Citizen Science',
      'welcome_message': 'Welcome to the FFWC App',
      'mobile_no_hint': 'Enter Mobile Number',
      'login_btn': 'Login',

      //Otp Page
      'otp_title': 'OTP VERIFICATION',
      'otp_message': 'Enter the OTP sent to:',
      'wait': 'Wait ',
      'after_wait': ' seconds to send new code.',
      'resend_otp': 'RESEND CODE',
      'otp_btn': 'Send OTP',

      //Dashboard
      'location_text': 'Mirpur DOHS, Dhaka, Bangladesh',
      'temperature': '32',
      'base': '°C',
      'low': '28°C',
      'high': '35°C',
      'wind': '15%',
      'weather_condition': 'Pretty Cloudy',
      'feels_like': 'Feels Like ',
      'marquee_text': '🚨 Flood Alert: (23 June 2025) Water levels in the Teesta, Dharla, and Dudhkumar rivers may rise over the next 2 days and may flow near the warning level (close to danger level) in the next 48 hours. ✦✦ See daily reports for detailed forecasts.',

      //Profile
      'profile_title': 'Profile',
      'profile_info': 'Profile Info',
      'settings': 'Settings',
      'profile_logout': 'Logout',
      'profile_info_name': 'Full Name',
      'profile_info_email': 'Email Address',
      'profile_info_address': 'Address',
      'profile_info_update_button': 'Update Profile Info',
      'profile_language_select': 'Language',
      'theme_select': 'Select Theme',
      'profile_logout_text': 'Logging out? We will be here when you are back!',
      'confirm_btn': 'Confirm',

      // Additional strings
      'station_condition': 'Station Condition',
      'other_features': 'Other Features',
      'severe_flood': 'Severe Flood',
      'flood': 'Flood',
      'warning': 'Warning',
      'normal': 'Normal',
      'alert_details': 'Forecast Trend',
      'location_label': 'Name this location',
      'location_hint': 'e.g., Home, Office',
      'save_btn': 'Save',
      'severe_mz': 'More than 1 m above danger level',
      'flood_mz': 'Its Above danger level',
      'warning_mz': 'Within 50 cm below danger level',
      'normal_mz': 'More than 50 cm below danger level',
      'general_mz': 'All Station Information Here',
      'forecast_bulletin': 'Forecast & Bulletin',
      'annual_reports': 'Annual Reports',
      'menu_report': 'Reports',
      'menu_manual': 'User\nManual',
      'menu_link': 'Useful\nLink',
      'menu_settings': 'Settings',
      'menu_about_us': 'About Us',
      'menu_contact': 'Contact Us',
      'rainfall_info': 'Rainfall Information',
      'water_level_forecast': 'Water Level Forecast',
      'water_level_research': 'Water Level Research',
      'other': 'Other',
      'inundation_map': 'Inundation Map',
      'rainfall_map': 'Rainfall Map',

      //Station information
      'last_update_news': 'Last Update: Sunday, 24 June 2024, 9:00 PM',
      'map_view': 'Map View',
      'list_view': 'List View',
      'search_text': 'Search by Station Name',
      'no_results_found': 'No results found',

      //Pdf Page
      'pdf_page': 'PDF Preview',
      'go_to_page': 'Go to Page',
      'page_number': 'Enter Page Number',
      'cancel': 'Cancel',
      'go': 'Go',

      //-------------/// Water Watch App ///-------------//
      'water_watch_app': 'Water Watch App',
      'tool': 'tool',
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'change_password': 'Change Mobile No',
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'profile_title': 'Profile',
      'profile_info': 'Profile Info',
      'profile_info_name': 'Full Name',
      'profile_info_email': 'Email Address',
      'profile_info_address': 'Address',
      'profile_info_update_button': 'Update Profile Info',
      'profile_logout': 'Logout',
      'profile_logout_text': 'Logging out? We will be here when you are back!',
      'dashboard_sidebar_important_video': 'App Manual',
      'dashboard_sidebar_about_us': 'About Us',
      'mission': 'Mission',
      'vision': 'Vision',
      'organogram': 'Organogram',
      'professionals': 'Professionals',
      'citizen_charter': 'Citizen Charter',
      'dashboard_sidebar_privacy_policy': 'Privacy Policy',
      'dashboard_rainfall': 'Rainfall',
      'dashboard_humidity': 'Humidity',
      'dashboard_wind': 'Wind Speed',
      'dashboard_time_good_morning': "Good Morning",
      'dashboard_time_good_noon': "Good Noon",
      'dashboard_time_good_afternoon': "Good Afternoon",
      'dashboard_time_good_evening': "Good Evening",
      'dashboard_time_good_night': "Good Night",
      'dashboard_weather_forecast': 'Weather\nForecast',
      'dashboard_weather_alert': 'Weather\nAlert',
      'dashboard_flood_forecast': 'Flood\nForecast',
      'dashboard_crop_advisory': 'Crop\nAdvisory',
      'dashboard_pest_disease': 'Disease\nAlert',
      'dashboard_pest_disease_information': 'Disease\nInformation',
      'dashboard_task_reminder': 'Task\nReminder',
      'dashboard_advisory_bulletin': 'Advisory\nBulletin',
      'community_connection': 'Community\nConnection',
      'weather_forecast': 'Weather Forecast',
      'wf_title': 'Weather Forecast',
      'wf_subtitle': 'Weather forecast for next 10 days',
      'wf_temp': 'Temparature',
      'wf_rf': 'Rainfall',
      'wf_rh': 'Humidity',
      'wf_wind': 'Wind Speed',
      'survey_data': 'Survey Data',
      'today_weather': 'Today\'s Weather',
      'landslide_frequency': 'Landslide Frequency',
      'landslide_frequency_overtime': 'Frequency Over Time',
      'my_survey': 'My Surveys',
      'survey_question': 'Survey Question',
      'survey_success': 'Survey submitted successfully',
      'survey_status': 'Survey Status',
      'survey_status_msg': 'This survey is already completed',
      'no_surveys': 'No surveys found',
      'create_survey': 'Create Survey',
      'survey_title': 'Survey Title',
      'enter_title': 'Enter title',
      'validation': 'Validation',
      'title_required': 'Title is required',
      'create_btn': 'Create',
      'instructions': 'Instructions',
      'survey_instructions': 'Select a place where the event happened.\n\nYou can tap on the map to select the location.\nYou can also drag the marker to fine-tune it.',
      'ok': 'OK',
      'no_questions': 'No questions found',
      'select_location': 'Select Location',
      'location_selected': 'Event Location',
      'latitude': 'Latitude: ',
      'longitude': 'Longitude: ',
      'distance_location': 'Distance from your location:',
      'again_btn': 'Again',
      'distance_snackbar': 'Distance from your location being copied: ',
      'delete_survey': 'Delete Survey !',
      'delete_survey_msg': 'Are you sure you want to delete this survey?',
      'yes': 'YES',
      'no': 'NO',
      'upload_failed': 'Upload failed',
      'upload_failed_msg': 'Image could\'nt upload. Image size more then 2 MB',
      'notification': 'Notification',
      'alert': 'Alert',
      'time': 'Time',
      'measurement': 'Measurement',
      'station': 'Station',
      'status': 'Status',
      'media': 'Media',
      'menu': 'Menu',
      'menu_title': 'Menu Item',
      'all': 'All',
      'close': 'Close',
      'rainfall_appbar_title': 'Rainfall Information',
      'data_load_indicator': 'Loading data...',
      'map_load_indicator': 'Loading map data...',
      'last_update_mz': 'Last Update: ',
      'search_hint': 'Search by Station Name',
      'station_name_title': 'Station Name: ',
      'river_name_title': 'River Name: ',
      'basin_name_title': 'Basin Name: ',
      'monthly_cumulative': 'Monthly Cumulative: ',
      'last_rainfall_table_heading': 'Last 10 Days Rainfall Data',
      'date': 'Date',
      'rainfall': 'Rainfall (mm)',
      'rainfall_distribute': 'Rainfall Distribution (mm)',
      'see_more': 'See More',
      'see_less': 'See Less',
      'last_rainfall_graph_heading': 'Last 10 Days Rainfall Graph',

      'water_level_appbar_title': 'Water level Research',
      'danger_level_title': 'Danger Level: ',
      'water_level_list_item': 'Water level: ',
      'rainfall_item': 'Rainfall: ',
      'last_water_level_table_heading': 'Last Water level Data',
      'water_level': 'Water level (mMSL)',
      'last_water_level_graph_heading': 'Last Water level Graph (mMSL)',

      'water_level_forecast_appbar_title': 'Water Level Forecast',
      'empty_data': 'No data found yet!',
      'subtitle_station': 'View & add Data',

      'rainfall_date': 'Rainfall Date: ',
      'legend_no_data': 'No data',
      'legend_value1': '00',
      'legend_value2': '0.1-49.9',
      'legend_value3': '50-99.9',
      'legend_value4': '≥100',

      'color_legend_value1': '0-0.1',
      'color_legend_value2': '0.1-3',
      'color_legend_value3': '3-10',
      'color_legend_value4': '10-20',
      'color_legend_value5': '20-40',
      'color_legend_value6': '40-60',
      'color_legend_value7': '60-80',
      'color_legend_value8': '80-100',
      'color_legend_value9': '100-200',
      'color_legend_value10': '≥200',

      'division': 'Division: ',
      'district': 'District: ',
      'upazila': 'Upazilla: ',
      'last_3_hour': 'Last 3 hours: ',
      'rise_fall_title': 'Last 24 hours Rise/Fall: ',
      'last_24_rainfall': 'Last 24 hours rainfall: ',
      'recorded_rainfall': 'Last recorded: ',
      'monthly_normal_rainfall': 'This month rainfall: ',
      'monthly_hoghest_rainfall': 'This month highest rainfall: ',
      'alert_text': 'Alert: ',
      'record': 'Record',
      'sms': 'SMS',
      'welcome': 'Welcome,',
      'my_record': "My Record",
      "add_record": "Add Record",
      "history_title": "History",
      "graph_title" :"Graph",
      "time_header": "Time",
      "water_level_heder": "Water Level",
      "status_header": "Action",
      "update": "Update",
      "delete": "Delete",
      "confirm_delete_title": "Confirm Delete",
      "confrim_delete_msg": "Are you sure you want to delete this record?",
      "day_of_week": "Day of Week",
      "select_date": "Select Date",
      "date_msg": "By default today's date is selected, you can adjust it by previous 7 days as well.",
      "measurement_value": "Measurement",
      "send_record_btn": "Send Record",
      "my_record_title": "My Records",
      "send_sms_title": "Send SMS",
      "confirm_text": 'Confirm?',
      "log_out_alert" : 'Are you sure ypu want to log Out?',
      'log_out' : 'Logout',
      'my_profile': 'My Profile',
      'first_name_label': 'First Name',
      'first_name_hint': 'Enter First Name',
      'last_name_label' : 'Last Name',
      'last_name_hint': 'Enter Last Name',
      'station_list_view_only': 'Station List (View Only)',
      'mobile_view_only': 'Mobile (View Only)',
      'verified': 'Verified',
      'profile_info_address_hint' : 'Enter detail Address',
      'annual_flood_report': 'Annual Flood Report',
      'user_manual': 'User Manual',
      'useful_links': 'Useful Links',
      'your_locations': 'Your Locations',
      'authorize_text': 'Only for Authorized User',
      'select_parameter': 'Select Parameter',
      'select_station': 'Select Station',
      'add_location': 'Add New Location',
      'location_list': 'Locations',
      'delete_error': 'Cannot Delete',
      'delete_error_msg': 'Current location cannot be deleted.',
      'canceled': 'Canceled',
      'canceled_hint': 'No name provided',
      'success_title': 'Success',
      'success_msg': 'Location saved and selected',
      'alert_title': 'Weather Forecast Trend',
      'server_maintenance_msg': 'Server Under Maintenance',
      'error': 'Error',
      'error_msg1': 'Failed to fetch forecast data',
      'error_msg2': 'An error occurred while fetching forecast data',
      '24_hours_rainfall': '24 Hours Rainfall: ',
      'rainfall_unit': '(mm)',
      'recorded_at': 'Recorded At: ',
      'current_month_normal_rainfall': 'Normal rainfall for this month: ',
      'current_month_max_rainfall': 'Maximum rainfall for this month: ',

    },
    'bn_BD': {

      //Bottom Nav Bar
      'home': 'হোম',
      'flood_info': 'বন্যা তথ্য',
      'flood_alert': 'বন্যা সতর্কতা',
      'profile': 'প্রোফাইল',

      //Login Page
      'app_name': 'এফএফডব্লিউসি অ্যাপ',
      'welcome_login': 'লগইন',
      'login_greetings': 'সিটিজেন সেয়েন্সে স্বাগত',
      'welcome_message': 'এফএফডব্লিউসি অ্যাপে আপনাকে স্বাগতম',
      'mobile_no_hint': 'মোবাইল নম্বর',
      'login_btn': 'লগইন করুন',

      //Otp Page
      'otp_title': 'ওটিপি যাচাইকরণ',
      'otp_message': 'আপনার ওটিপি লিখুন যা পাঠানো হয়েছে: ',
      'wait': 'অপেক্ষা করুন ',
      'after_wait': ' সেকেন্ড নতুন কোড পাঠানোর জন্য',
      'resend_otp': 'কোড পুনরায় পাঠান',
      'otp_btn': 'OTP পাঠান',

      //Dashboard
      'location_text': 'মিরপুর ডিওএইচএস, ঢাকা, বাংলাদেশ',
      'temperature': '৩২',
      'base': '°সে',
      'low': '২৮°সে',
      'high': '৩৫°সে',
      'wind': '১৫%',
      'weather_condition': 'আংশিক মেঘলা',
      'feels_like': 'মনে হচ্ছে ',
      'marquee_text': '🚨 বন্যা সতর্কতা: (২৩ জুন ২০২৫) তিস্তা, ধরলা ও দুধকুমার নদীসমূহের পানি আগামী ০২ দিন বৃদ্ধি পেতে পারে এবং আগামী ৪৮ ঘণ্টায় তিস্তা নদীর পানি সতর্কসীমায় (বিপদসীমার কাছাকাছি) প্রবাহিত হতে পারে। ✦✦ বিস্তারিত পূর্বাভাসের জন্য দৈনিক প্রতিবেদন দেখুন।',

      //Profile
      'profile_title': 'প্রোফাইল',
      'profile_info': 'প্রোফাইল তথ্য',
      'settings': 'সেটিংস',
      'alert_details': 'পূর্বাভাস প্রবণতা',
      'profile_logout': 'লগ আউট',
      'profile_info_name': 'পুরো নাম',
      'profile_info_email': 'ইমেল ঠিকানা',
      'profile_info_address': 'ঠিকানা',
      'profile_info_update_button': 'প্রোফাইল তথ্য হালনাগাদ করুন',
      'profile_language_select': 'ভাষা নির্বাচন',
      'theme_select': 'থিম নির্বাচন করুন',
      'profile_logout_text': 'লগ আউট করতে চান? আমরা আবার দেখা হবে যখন আপনি ফিরে আসবেন!',
      'confirm_btn': 'নিশ্চিত করুন',

      // Additional strings
      'station_condition': 'স্টেশনের বর্তমান অবস্থা',
      'other_features': 'অন্যান্য বৈশিষ্ট্য',
      'severe_flood': 'তীব্র বন্যা',
      'flood': 'বন্যা',
      'warning': 'সতর্কতা',
      'normal': 'সাধারণ',
      'severe_mz': 'বিপদসীমার ১ মিটার উপরে',
      'flood_mz': 'পানি বিপদসীমার উপরে',
      'warning_mz': 'বিপদসীমার ৫০ সেন্টিমিটার নিচে',
      'normal_mz': 'বিপদসীমার ৫০ সেন্টিমিটার নিচে',
      'general_mz': 'সকল স্টেশনের তথ্য এখানে',
      'forecast_bulletin': 'পূর্বাভাস ও বুলেটিন',
      'annual_reports': 'বার্ষিক প্রতিবেদন',
      'rainfall_info': 'বৃষ্টিপাতের তথ্য',
      'water_level_forecast': 'পানি সমতলের পূর্বাভাস',
      'water_level_research': 'পানি সমতলের পর্যবেক্ষন',
      'other': 'অন্যান্য',
      'inundation_map': 'জলাবদ্ধতা মানচিত্র',
      'rainfall_map': 'বৃষ্টিপাতের মানচিত্র',

      //Station information
      'last_update_news': 'সর্বশেষ আপডেট: রবিবার ২৪ জুন, ২০২৪ রাত ৯.০০ টা',
      'map_view': 'মানচিত্র দেখুন',
      'list_view': 'তালিকা দেখুন',
      'search_text': 'স্টেশন অনুসারে অনুসন্ধান করুন',
      'no_results_found': 'কোন ফলাফল পাওয়া যায়নি',

      //Pdf Page
      'pdf_page': 'পিডিএফ প্রিভিউ',
      'go_to_page': 'পৃষ্ঠায় যান',
      'page_number': 'পৃষ্ঠা নম্বর লিখুন',
      'cancel': 'বাতিল',
      'go': 'যাও',

      'menu_report': 'প্রতিবেদন',
      'menu_manual': 'ব্যবহার\nবিধি',
      'menu_link': 'প্রয়োজনীয়\nলিঙ্ক',
      'menu_settings': 'সেটিংস',
      'menu_about_us': 'আমাদের\nসম্পর্কে',
      'menu_contact': 'যোগাযোগ\nকরুণ',

      //-------------/// Water Watch App ///-------------//
      'water_watch_app': 'ওয়াটার ওয়াচ অ্যাপ',
      'title': 'LandSlide Report',
      'tool': 'tool',
      'settings': 'সেটিংস',
      'dashboard': 'ড্যাশবোর্ড',
      'change_password': 'মোবাইল নম্বর পরিবর্তন',
      'help_center': 'সাহায্য কেন্দ্র',
      'faq': 'জিজ্ঞাসিত প্রশ্নাবলী',
      'profile_title': 'প্রোফাইল',
      'profile_info': 'প্রোফাইল বিত্রান্ত',
      'profile_info_name': 'পুরো নাম',
      'profile_info_email': 'ইমেল এড্রেস',
      'profile_info_address': 'ঠিকানা',
      'profile_info_update_button': 'প্রোফাইল ইনফো হালনাগাদ করুণ',
      'profile_logout': 'লগ আউট',
      'profile_logout_text': 'তুমি কী প্রস্থান করতে চাও? আমাদের আবার দেখা হবে তুমি যখন ফিরে আসবে।',
      'dashboard_sidebar_important_video': 'অ্যাপ ম্যানুয়াল',
      'mission': 'মিশন',
      'vision': 'ভিশন',
      'organogram': 'অর্গানোগ্রাম',
      'professionals': 'কর্মকর্তা',
      'citizen_charter': 'নাগরিক সনদ',
      'dashboard_sidebar_about_us': 'আমাদের সম্পর্কে',
      'dashboard_sidebar_privacy_policy': 'গোপনীয়তা নীতি',
      'dashboard_rainfall': 'বৃষ্টিপাত',
      'dashboard_humidity': 'আর্দ্রতা',
      'dashboard_wind': 'বাতাসের গতি',
      'dashboard_time_good_morning': "শুভ সকাল",
      'dashboard_time_good_noon': "শুভ দুপুর",
      'dashboard_time_good_afternoon': "শুভ বিকাল",
      'dashboard_time_good_evening': "শুভ সন্ধ্যা",
      'dashboard_time_good_night': "শুভ রাত্রি",
      'dashboard_weather_forecast': 'আবহাওয়া\nপূর্বাভাস',
      'dashboard_weather_alert': 'আবহাওয়া\nসতর্কবার্তা',
      'dashboard_flood_forecast': 'বন্যা\nপূর্বাভাস',
      'dashboard_crop_advisory': 'ফসল\nপরামর্শ',
      'dashboard_pest_disease': 'রোগের\nসতর্কতা',
      'dashboard_pest_disease_information': 'রোগের\nতথ্য',
      'dashboard_task_reminder': 'টাস্ক\nরিমাইন্ডার',
      'dashboard_advisory_bulletin': 'এডভাইজারি\nবুলেটিন',
      'community_connection': 'জনসাধারণ\nসংযোগ',
      'weather_forecast': 'আবহাওয়া পূর্বাভাস',
      'wf_title': 'আবহাওয়া পূর্বাভাস',
      'wf_subtitle': 'পরবর্তী ১০ দিনের আবহাওয়া পূর্বাভাস',
      'wf_temp': 'তাপমাত্রা',
      'wf_rf': 'বৃষ্টিপাত',
      'wf_rh': 'আপেক্ষিক আর্দ্রতা',
      'wf_wind': 'বাতাসের গতি',
      'survey_data': 'জরিপ তথ্য',
      'today_weather': 'আজকের আবহাওয়া',
      'landslide_frequency': 'ভূমিধসের পুনরাবৃত্তির হার',
      'landslide_frequency_overtime': 'সময়ের সাথে পুনরাবৃত্তির হার',
      'my_survey': 'আমার জরিপ সমূহ',
      'survey_question': 'জরিপের প্রশ্ন',
      'survey_success': 'জরিপ সফলভাবে জমা হয়েছে',
      'survey_status': 'জরিপের অবস্থা',
      'no_surveys': 'কোন জরিপ পাওয়া যায়নি',
      'survey_status_msg': 'এই জরিপটি ইতিমধ্যে সম্পন্ন হয়েছে',
      'create_survey': 'জরিপ তৈরি করুন',
      'survey_title': 'জরিপের শিরোনাম',
      'enter_title': 'শিরোনাম লিখুন',
      'validation': 'ভ্যালিডেশন',
      'title_required': 'শিরোনাম আবশ্যক',
      'create_btn': 'তৈরি করুন',
      'select_location': 'অবস্থান নির্বাচন করুন',
      'instructions': 'নির্দেশাবলী',
      'survey_instructions': 'একটি স্থান নির্বাচন করুন যেখানে ঘটনাটি ঘটেছে।\n\nআপনি মানচিত্রে ট্যাপ করে অবস্থান নির্বাচন করতে পারেন।\nআপনি ট্যাপ করার পর এটি আরও সঠিকভাবে সেট করার জন্য পিন মার্কারটিকে সরা নড়া করতে পারেন।',
      'ok': 'ওকে',
      'no_questions': 'কোন প্রশ্ন পাওয়া যায়নি',
      'location_selected': 'আপনার ঘটনাস্থল',
      'latitude': 'অক্ষাংশ: ',
      'longitude': 'দ্রাঘিমাংশ: ',
      'distance_location': 'আপনার অবস্থান থেকে দূরত্ব:',
      'again_btn': 'আবার',
      'distance_snackbar': 'আপনার অবস্থান থেকে দূরত্ব কপি করা হয়েছে: ',
      'delete_survey': 'জরিপ মুছুন !',
      'delete_survey_msg': 'আপনি কি নিশ্চিত যে আপনি এই জরিপটি মুছতে চান?',
      'yes': 'হ্যাঁ',
      'no': 'না',
      'upload_failed': 'আপলোড ব্যর্থ',
      'upload_failed_msg': 'ছবি আপলোড করতে ব্যর্থ। ছবি সাইজ ২ এমবির বেশি',
      'notification': 'নোটিফিকেশন',
      'alert': 'সতর্কতা',
      'time': 'সময়',
      'measurement': 'পরিমাপ',
      'station': 'স্টেশন',
      'status': 'অবস্থা',
      'media': 'মিডিয়া',
      'menu': 'মেনু',
      'menu_title': 'মেনু তালিকা',
      'all': 'সকল',
      'close': 'বন্ধ করুন',
      'rainfall_appbar_title': 'বৃষ্টিপাতের তথ্য',
      'data_load_indicator': 'তথ্য লোড হচ্ছে...',
      'map_load_indicator': 'মানচিত্র লোড হচ্ছে...',
      'alert_text': 'বার্তা: ',
      'last_update_mz': 'সর্বশেষ আপডেট: ',
      'search_hint': 'স্টেশন অনুসারে অনুসন্ধান করুন',
      'station_name_title': 'স্টেশন নাম: ',
      'river_name_title': 'নদীর নাম: ',
      'basin_name_title': 'বেসিন নাম: ',
      'monthly_cumulative': 'মাসিক সঞ্চিত: ',
      'last_rainfall_table_heading': 'গত ১০ দিনের বৃষ্টিপাতের তথ্য',
      'date': 'তারিখ',
      'rainfall': 'বৃষ্টিপাত (মিমি)',
      'rainfall_distribute': 'বৃষ্টিপাত বন্টন (মিমি)',
      'see_more': 'আরো দেখুন',
      'see_less': 'কম দেখুন',
      'last_rainfall_graph_heading': 'গত ১০ দিনের বৃষ্টিপাতের গ্রাফ',
      'water_level_appbar_title': 'পর্যবেক্ষন করা পানির স্তর',
      'danger_level_title': 'বিপদের মাত্রা: ',
      'water_level_list_item': 'পানির স্তর: ',
      'rainfall_item': 'বৃষ্টিপাত: ',
      'last_water_level_table_heading': 'সর্বশেষ পানির স্তরের অবস্থা',
      'water_level': 'পানির স্তর (mMSL)',
      'last_water_level_graph_heading': 'সর্বশেষ পানির গ্রাফ (mMSL)',
      'water_level_forecast_appbar_title': 'পানি সমতলের পূর্বাভাস',
      'rainfall_date': 'বৃষ্টিপাতের তারিখ: ',
      'subtitle_station': 'ডেটা দেখুন ও যোগ করুন',
      'empty_data': 'কোন তথ্য পাওয়া যায় নি!',

      'legend_no_data': 'তথ্য নেই',
      'legend_value1': '০০',
      'legend_value2': '০.১-৪৯.৯',
      'legend_value3': '৫০-৯৯.৯',
      'legend_value4': '≥১০০',

      'color_legend_value1': '০-০.১',
      'color_legend_value2': '০.১-৩',
      'color_legend_value3': '৩-১০',
      'color_legend_value4': '১০-২০',
      'color_legend_value5': '২০-৪০',
      'color_legend_value6': '৪০-৬০',
      'color_legend_value7': '৬০-৮০',
      'color_legend_value8': '৮০-১০০',
      'color_legend_value9': '১০০-২০০',
      'color_legend_value10': '≥২০০',

      'division': 'বিভাগ: ',
      'district': 'জেলা: ',
      'upazila': 'উপজেলা: ',
      'last_3_hour': 'গত ৩ ঘন্টা: ',
      'rise_fall_title': 'গত ২৪ ঘন্টার উত্থান/পতন: ',
      'last_24_rainfall': 'গত ২৪ ঘন্টার বৃষ্টিপাত: ',
      'recorded_rainfall': 'রেকর্ড করা হয়েছে: ',
      'monthly_normal_rainfall': 'এই মাসে স্বাভাবিক বৃষ্টিপাত: ',
      'monthly_hoghest_rainfall': 'এই মাসে সর্বাধিক বৃষ্টিপাত: ',
      'record': 'রেকর্ড',
      'sms': 'এস.এম.এস',
      'welcome': 'স্বাগতম,',
      'my_record': 'আমার রেকর্ড',
      "add_record": "রেকর্ড যোগ করুণ",
      "history_title" :"রেকর্ড সমূহ",
      "graph_title" :"গ্রাফ",
      "time_header": "সময়",
      "water_level_heder": "পানির স্তর",
      "status_header": "একশন",
      "update": "হালনাগাদ",
      "delete": "মুছুন",
      'canceled': 'বাতিল',
      'delete_hint': 'রেকর্ড মুছে ফেলুন ',
      "confirm_delete_title": "মুছুন নিশ্চিত করুণ",
      "confirm_delete_msg": "আপনি কি নিশ্চিত যে আপনি এই রেকর্ড মুছে ফেলতে চান?",
      "day_of_week": "সাপ্তাহিক দিন",
      "select_date": "তারিখ নির্বাচন করুন",
      "date_msg": "ডিফল্ট আজকের তারিখ দেখায়, গত ৭ দিন পর্যন্ত সামঞ্জস্য করুন।",
      "measurement_value": "পরিমাপ",
      "send_record_btn": "রেকর্ড পাঠান",
      "send_sms_title": "এস.এম.এস পাঠান",
      "confirm_text": 'নিশ্চিত?',
      "log_out_alert" : 'আপনি লগআউট করতে চান?',
      'log_out' : 'লগআউট',
      'my_profile': 'আমার প্রোফাইল',
      'first_name_label': 'প্রথম নাম',
      'first_name_hint': 'প্রথম নাম এন্ট্রি করান',
      'last_name_label' : 'শেষের নাম',
      'last_name_hint': 'শেষের নাম এন্ট্রি করান',
      'station_list_view_only': 'স্টেশন সমূহ (শুধু দেখা)',
      'mobile_view_only': 'মোবাইল (শুধু দেখা)',
      'verified': 'যাচাইকৃত',
      'profile_info_address_hint' : 'আপনার পূর্ন ঠিকানা দিন',
      'annual_flood_report': 'বার্ষিক বন্যা প্রতিবেদন',
      'user_manuals': 'ব্যবহার নির্দেশিকা',
      'useful_links': 'গুরুত্বপূর্ণ লিংকসমূহ',
      'your_locations': 'আপনার অবস্থান সমূহ',
      'authorize_text': 'শুধুমাত্র অনুমোদিত ব্যবহারকারীর জন্য',
      'select_parameter': 'প্যারামিটার নির্বাচন করুন',
      'select_station': 'স্টেশন নির্বাচন করুন',
      'location_label': 'লোকেশন এর নাম দিন',
      'location_hint': 'বাসা, অফিস, স্কুল ইত্যাদি',
      'save_btn': 'সেভ করুন',
      'add_location': 'লোকেশন যোগ করুন',
      'location_list': 'লোকেশন সমূহ',
      'canceled_hint': 'কোন নাম প্রদান করা হয়নি',
      'success_title': 'সফল',
      'success_msg': 'লোকেশন সেভ এবং সিলেক্ট করা হয়েছে',
      'alert_title': 'আবহাওয়া পূর্বাভাসের ধারা',
      'server_maintenance_msg': 'সার্ভার রক্ষণাবেক্ষণ এর কাজ চলছে',
      'error': 'ত্রুটি',
      'error_msg1': 'তথ্য আনতে ব্যর্থ হয়েছে',
      'error_msg2': 'সার্ভার রক্ষণাবেক্ষণ এর জন্যে তথ্য আনতে ব্যর্থ হয়েছে',
      '24_hours_rainfall': 'গত ২৪ ঘন্টার বৃষ্টিপাত: ',
      'rainfall_unit': '(মিমি)',
      'recorded_at': 'রেকর্ড করা হয়েছে: ',
      'current_month_normal_rainfall': 'এই মাসে স্বাভাবিক বৃষ্টিপাত: ',
      'current_month_max_rainfall': 'এই মাসে সর্বাধিক বৃষ্টিপাত: ',

    }
  };
}
